// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleProtoObjectsForTest.proto

package com.tosan.redissoncodectest.protoEntities;

public interface ProtoObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.NullValue null_value = 1;</code>
   * @return Whether the nullValue field is set.
   */
  boolean hasNullValue();
  /**
   * <code>.NullValue null_value = 1;</code>
   * @return The enum numeric value on the wire for nullValue.
   */
  int getNullValueValue();
  /**
   * <code>.NullValue null_value = 1;</code>
   * @return The nullValue.
   */
  NullValue getNullValue();

  /**
   * <code>double double_value = 2;</code>
   * @return Whether the doubleValue field is set.
   */
  boolean hasDoubleValue();
  /**
   * <code>double double_value = 2;</code>
   * @return The doubleValue.
   */
  double getDoubleValue();

  /**
   * <code>float float_value = 3;</code>
   * @return Whether the floatValue field is set.
   */
  boolean hasFloatValue();
  /**
   * <code>float float_value = 3;</code>
   * @return The floatValue.
   */
  float getFloatValue();

  /**
   * <code>string string_value = 4;</code>
   * @return Whether the stringValue field is set.
   */
  boolean hasStringValue();
  /**
   * <code>string string_value = 4;</code>
   * @return The stringValue.
   */
  String getStringValue();
  /**
   * <code>string string_value = 4;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>bool bool_value = 5;</code>
   * @return Whether the boolValue field is set.
   */
  boolean hasBoolValue();
  /**
   * <code>bool bool_value = 5;</code>
   * @return The boolValue.
   */
  boolean getBoolValue();

  /**
   * <code>int32 int_value = 6;</code>
   * @return Whether the intValue field is set.
   */
  boolean hasIntValue();
  /**
   * <code>int32 int_value = 6;</code>
   * @return The intValue.
   */
  int getIntValue();

  /**
   * <code>int64 long_value = 7;</code>
   * @return Whether the longValue field is set.
   */
  boolean hasLongValue();
  /**
   * <code>int64 long_value = 7;</code>
   * @return The longValue.
   */
  long getLongValue();

  public ProtoObject.KindCase getKindCase();
}
