// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleProtoObjectsForTest.proto

package com.tosan.redissoncodectest.protoEntities;

public interface SampleProtoObjectForTestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SampleProtoObjectForTest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double doubleTypeField = 1;</code>
   * @return The doubleTypeField.
   */
  double getDoubleTypeField();

  /**
   * <code>float floatTypeField = 2;</code>
   * @return The floatTypeField.
   */
  float getFloatTypeField();

  /**
   * <code>int32 intTypeField = 3;</code>
   * @return The intTypeField.
   */
  int getIntTypeField();

  /**
   * <code>int64 longTypeField = 4;</code>
   * @return The longTypeField.
   */
  long getLongTypeField();

  /**
   * <code>bool boolTrueField = 5;</code>
   * @return The boolTrueField.
   */
  boolean getBoolTrueField();

  /**
   * <code>bool boolFalseField = 6;</code>
   * @return The boolFalseField.
   */
  boolean getBoolFalseField();

  /**
   * <code>string stringTypeField = 7;</code>
   * @return The stringTypeField.
   */
  String getStringTypeField();
  /**
   * <code>string stringTypeField = 7;</code>
   * @return The bytes for stringTypeField.
   */
  com.google.protobuf.ByteString
      getStringTypeFieldBytes();

  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  java.util.List<ProtoObject>
      getListObjectTypeFieldList();
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  ProtoObject getListObjectTypeField(int index);
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  int getListObjectTypeFieldCount();
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  java.util.List<? extends ProtoObjectOrBuilder>
      getListObjectTypeFieldOrBuilderList();
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  ProtoObjectOrBuilder getListObjectTypeFieldOrBuilder(
      int index);
}
