// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleProtoObjectsForTest.proto

package com.tosan.redissoncodectest.protoEntities;

/**
 * Protobuf type {@code SampleProtoObjectForTest}
 */
public final class SampleProtoObjectForTest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SampleProtoObjectForTest)
    SampleProtoObjectForTestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SampleProtoObjectForTest.newBuilder() to construct.
  private SampleProtoObjectForTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SampleProtoObjectForTest() {
    stringTypeField_ = "";
    listObjectTypeField_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SampleProtoObjectForTest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SampleProtoObjectForTest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            doubleTypeField_ = input.readDouble();
            break;
          }
          case 21: {

            floatTypeField_ = input.readFloat();
            break;
          }
          case 24: {

            intTypeField_ = input.readInt32();
            break;
          }
          case 32: {

            longTypeField_ = input.readInt64();
            break;
          }
          case 40: {

            boolTrueField_ = input.readBool();
            break;
          }
          case 48: {

            boolFalseField_ = input.readBool();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            stringTypeField_ = s;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              listObjectTypeField_ = new java.util.ArrayList<ProtoObject>();
              mutable_bitField0_ |= 0x00000001;
            }
            listObjectTypeField_.add(
                input.readMessage(ProtoObject.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        listObjectTypeField_ = java.util.Collections.unmodifiableList(listObjectTypeField_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SampleProtoObjectsForTest.internal_static_SampleProtoObjectForTest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SampleProtoObjectsForTest.internal_static_SampleProtoObjectForTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SampleProtoObjectForTest.class, Builder.class);
  }

  public static final int DOUBLETYPEFIELD_FIELD_NUMBER = 1;
  private double doubleTypeField_;
  /**
   * <code>double doubleTypeField = 1;</code>
   * @return The doubleTypeField.
   */
  @Override
  public double getDoubleTypeField() {
    return doubleTypeField_;
  }

  public static final int FLOATTYPEFIELD_FIELD_NUMBER = 2;
  private float floatTypeField_;
  /**
   * <code>float floatTypeField = 2;</code>
   * @return The floatTypeField.
   */
  @Override
  public float getFloatTypeField() {
    return floatTypeField_;
  }

  public static final int INTTYPEFIELD_FIELD_NUMBER = 3;
  private int intTypeField_;
  /**
   * <code>int32 intTypeField = 3;</code>
   * @return The intTypeField.
   */
  @Override
  public int getIntTypeField() {
    return intTypeField_;
  }

  public static final int LONGTYPEFIELD_FIELD_NUMBER = 4;
  private long longTypeField_;
  /**
   * <code>int64 longTypeField = 4;</code>
   * @return The longTypeField.
   */
  @Override
  public long getLongTypeField() {
    return longTypeField_;
  }

  public static final int BOOLTRUEFIELD_FIELD_NUMBER = 5;
  private boolean boolTrueField_;
  /**
   * <code>bool boolTrueField = 5;</code>
   * @return The boolTrueField.
   */
  @Override
  public boolean getBoolTrueField() {
    return boolTrueField_;
  }

  public static final int BOOLFALSEFIELD_FIELD_NUMBER = 6;
  private boolean boolFalseField_;
  /**
   * <code>bool boolFalseField = 6;</code>
   * @return The boolFalseField.
   */
  @Override
  public boolean getBoolFalseField() {
    return boolFalseField_;
  }

  public static final int STRINGTYPEFIELD_FIELD_NUMBER = 7;
  private volatile Object stringTypeField_;
  /**
   * <code>string stringTypeField = 7;</code>
   * @return The stringTypeField.
   */
  @Override
  public String getStringTypeField() {
    Object ref = stringTypeField_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      stringTypeField_ = s;
      return s;
    }
  }
  /**
   * <code>string stringTypeField = 7;</code>
   * @return The bytes for stringTypeField.
   */
  @Override
  public com.google.protobuf.ByteString
      getStringTypeFieldBytes() {
    Object ref = stringTypeField_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      stringTypeField_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LISTOBJECTTYPEFIELD_FIELD_NUMBER = 8;
  private java.util.List<ProtoObject> listObjectTypeField_;
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  @Override
  public java.util.List<ProtoObject> getListObjectTypeFieldList() {
    return listObjectTypeField_;
  }
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  @Override
  public java.util.List<? extends ProtoObjectOrBuilder>
      getListObjectTypeFieldOrBuilderList() {
    return listObjectTypeField_;
  }
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  @Override
  public int getListObjectTypeFieldCount() {
    return listObjectTypeField_.size();
  }
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  @Override
  public ProtoObject getListObjectTypeField(int index) {
    return listObjectTypeField_.get(index);
  }
  /**
   * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
   */
  @Override
  public ProtoObjectOrBuilder getListObjectTypeFieldOrBuilder(
      int index) {
    return listObjectTypeField_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (doubleTypeField_ != 0D) {
      output.writeDouble(1, doubleTypeField_);
    }
    if (floatTypeField_ != 0F) {
      output.writeFloat(2, floatTypeField_);
    }
    if (intTypeField_ != 0) {
      output.writeInt32(3, intTypeField_);
    }
    if (longTypeField_ != 0L) {
      output.writeInt64(4, longTypeField_);
    }
    if (boolTrueField_ != false) {
      output.writeBool(5, boolTrueField_);
    }
    if (boolFalseField_ != false) {
      output.writeBool(6, boolFalseField_);
    }
    if (!getStringTypeFieldBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, stringTypeField_);
    }
    for (int i = 0; i < listObjectTypeField_.size(); i++) {
      output.writeMessage(8, listObjectTypeField_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (doubleTypeField_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, doubleTypeField_);
    }
    if (floatTypeField_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, floatTypeField_);
    }
    if (intTypeField_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, intTypeField_);
    }
    if (longTypeField_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, longTypeField_);
    }
    if (boolTrueField_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, boolTrueField_);
    }
    if (boolFalseField_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, boolFalseField_);
    }
    if (!getStringTypeFieldBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, stringTypeField_);
    }
    for (int i = 0; i < listObjectTypeField_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, listObjectTypeField_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SampleProtoObjectForTest)) {
      return super.equals(obj);
    }
    SampleProtoObjectForTest other = (SampleProtoObjectForTest) obj;

    if (Double.doubleToLongBits(getDoubleTypeField())
        != Double.doubleToLongBits(
            other.getDoubleTypeField())) return false;
    if (Float.floatToIntBits(getFloatTypeField())
        != Float.floatToIntBits(
            other.getFloatTypeField())) return false;
    if (getIntTypeField()
        != other.getIntTypeField()) return false;
    if (getLongTypeField()
        != other.getLongTypeField()) return false;
    if (getBoolTrueField()
        != other.getBoolTrueField()) return false;
    if (getBoolFalseField()
        != other.getBoolFalseField()) return false;
    if (!getStringTypeField()
        .equals(other.getStringTypeField())) return false;
    if (!getListObjectTypeFieldList()
        .equals(other.getListObjectTypeFieldList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOUBLETYPEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getDoubleTypeField()));
    hash = (37 * hash) + FLOATTYPEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getFloatTypeField());
    hash = (37 * hash) + INTTYPEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + getIntTypeField();
    hash = (37 * hash) + LONGTYPEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLongTypeField());
    hash = (37 * hash) + BOOLTRUEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolTrueField());
    hash = (37 * hash) + BOOLFALSEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBoolFalseField());
    hash = (37 * hash) + STRINGTYPEFIELD_FIELD_NUMBER;
    hash = (53 * hash) + getStringTypeField().hashCode();
    if (getListObjectTypeFieldCount() > 0) {
      hash = (37 * hash) + LISTOBJECTTYPEFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getListObjectTypeFieldList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SampleProtoObjectForTest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SampleProtoObjectForTest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SampleProtoObjectForTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SampleProtoObjectForTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SampleProtoObjectForTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SampleProtoObjectForTest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SampleProtoObjectForTest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SampleProtoObjectForTest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SampleProtoObjectForTest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SampleProtoObjectForTest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SampleProtoObjectForTest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SampleProtoObjectForTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SampleProtoObjectForTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SampleProtoObjectForTest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SampleProtoObjectForTest)
      SampleProtoObjectForTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SampleProtoObjectsForTest.internal_static_SampleProtoObjectForTest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SampleProtoObjectsForTest.internal_static_SampleProtoObjectForTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SampleProtoObjectForTest.class, Builder.class);
    }

    // Construct using com.tosan.redissoncodectest.protoEntities.SampleProtoObjectForTest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getListObjectTypeFieldFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      doubleTypeField_ = 0D;

      floatTypeField_ = 0F;

      intTypeField_ = 0;

      longTypeField_ = 0L;

      boolTrueField_ = false;

      boolFalseField_ = false;

      stringTypeField_ = "";

      if (listObjectTypeFieldBuilder_ == null) {
        listObjectTypeField_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        listObjectTypeFieldBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SampleProtoObjectsForTest.internal_static_SampleProtoObjectForTest_descriptor;
    }

    @Override
    public SampleProtoObjectForTest getDefaultInstanceForType() {
      return SampleProtoObjectForTest.getDefaultInstance();
    }

    @Override
    public SampleProtoObjectForTest build() {
      SampleProtoObjectForTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SampleProtoObjectForTest buildPartial() {
      SampleProtoObjectForTest result = new SampleProtoObjectForTest(this);
      int from_bitField0_ = bitField0_;
      result.doubleTypeField_ = doubleTypeField_;
      result.floatTypeField_ = floatTypeField_;
      result.intTypeField_ = intTypeField_;
      result.longTypeField_ = longTypeField_;
      result.boolTrueField_ = boolTrueField_;
      result.boolFalseField_ = boolFalseField_;
      result.stringTypeField_ = stringTypeField_;
      if (listObjectTypeFieldBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          listObjectTypeField_ = java.util.Collections.unmodifiableList(listObjectTypeField_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listObjectTypeField_ = listObjectTypeField_;
      } else {
        result.listObjectTypeField_ = listObjectTypeFieldBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SampleProtoObjectForTest) {
        return mergeFrom((SampleProtoObjectForTest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SampleProtoObjectForTest other) {
      if (other == SampleProtoObjectForTest.getDefaultInstance()) return this;
      if (other.getDoubleTypeField() != 0D) {
        setDoubleTypeField(other.getDoubleTypeField());
      }
      if (other.getFloatTypeField() != 0F) {
        setFloatTypeField(other.getFloatTypeField());
      }
      if (other.getIntTypeField() != 0) {
        setIntTypeField(other.getIntTypeField());
      }
      if (other.getLongTypeField() != 0L) {
        setLongTypeField(other.getLongTypeField());
      }
      if (other.getBoolTrueField() != false) {
        setBoolTrueField(other.getBoolTrueField());
      }
      if (other.getBoolFalseField() != false) {
        setBoolFalseField(other.getBoolFalseField());
      }
      if (!other.getStringTypeField().isEmpty()) {
        stringTypeField_ = other.stringTypeField_;
        onChanged();
      }
      if (listObjectTypeFieldBuilder_ == null) {
        if (!other.listObjectTypeField_.isEmpty()) {
          if (listObjectTypeField_.isEmpty()) {
            listObjectTypeField_ = other.listObjectTypeField_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListObjectTypeFieldIsMutable();
            listObjectTypeField_.addAll(other.listObjectTypeField_);
          }
          onChanged();
        }
      } else {
        if (!other.listObjectTypeField_.isEmpty()) {
          if (listObjectTypeFieldBuilder_.isEmpty()) {
            listObjectTypeFieldBuilder_.dispose();
            listObjectTypeFieldBuilder_ = null;
            listObjectTypeField_ = other.listObjectTypeField_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listObjectTypeFieldBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListObjectTypeFieldFieldBuilder() : null;
          } else {
            listObjectTypeFieldBuilder_.addAllMessages(other.listObjectTypeField_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SampleProtoObjectForTest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SampleProtoObjectForTest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private double doubleTypeField_ ;
    /**
     * <code>double doubleTypeField = 1;</code>
     * @return The doubleTypeField.
     */
    @Override
    public double getDoubleTypeField() {
      return doubleTypeField_;
    }
    /**
     * <code>double doubleTypeField = 1;</code>
     * @param value The doubleTypeField to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleTypeField(double value) {
      
      doubleTypeField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double doubleTypeField = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleTypeField() {
      
      doubleTypeField_ = 0D;
      onChanged();
      return this;
    }

    private float floatTypeField_ ;
    /**
     * <code>float floatTypeField = 2;</code>
     * @return The floatTypeField.
     */
    @Override
    public float getFloatTypeField() {
      return floatTypeField_;
    }
    /**
     * <code>float floatTypeField = 2;</code>
     * @param value The floatTypeField to set.
     * @return This builder for chaining.
     */
    public Builder setFloatTypeField(float value) {
      
      floatTypeField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float floatTypeField = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatTypeField() {
      
      floatTypeField_ = 0F;
      onChanged();
      return this;
    }

    private int intTypeField_ ;
    /**
     * <code>int32 intTypeField = 3;</code>
     * @return The intTypeField.
     */
    @Override
    public int getIntTypeField() {
      return intTypeField_;
    }
    /**
     * <code>int32 intTypeField = 3;</code>
     * @param value The intTypeField to set.
     * @return This builder for chaining.
     */
    public Builder setIntTypeField(int value) {
      
      intTypeField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 intTypeField = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntTypeField() {
      
      intTypeField_ = 0;
      onChanged();
      return this;
    }

    private long longTypeField_ ;
    /**
     * <code>int64 longTypeField = 4;</code>
     * @return The longTypeField.
     */
    @Override
    public long getLongTypeField() {
      return longTypeField_;
    }
    /**
     * <code>int64 longTypeField = 4;</code>
     * @param value The longTypeField to set.
     * @return This builder for chaining.
     */
    public Builder setLongTypeField(long value) {
      
      longTypeField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 longTypeField = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongTypeField() {
      
      longTypeField_ = 0L;
      onChanged();
      return this;
    }

    private boolean boolTrueField_ ;
    /**
     * <code>bool boolTrueField = 5;</code>
     * @return The boolTrueField.
     */
    @Override
    public boolean getBoolTrueField() {
      return boolTrueField_;
    }
    /**
     * <code>bool boolTrueField = 5;</code>
     * @param value The boolTrueField to set.
     * @return This builder for chaining.
     */
    public Builder setBoolTrueField(boolean value) {
      
      boolTrueField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolTrueField = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolTrueField() {
      
      boolTrueField_ = false;
      onChanged();
      return this;
    }

    private boolean boolFalseField_ ;
    /**
     * <code>bool boolFalseField = 6;</code>
     * @return The boolFalseField.
     */
    @Override
    public boolean getBoolFalseField() {
      return boolFalseField_;
    }
    /**
     * <code>bool boolFalseField = 6;</code>
     * @param value The boolFalseField to set.
     * @return This builder for chaining.
     */
    public Builder setBoolFalseField(boolean value) {
      
      boolFalseField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolFalseField = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolFalseField() {
      
      boolFalseField_ = false;
      onChanged();
      return this;
    }

    private Object stringTypeField_ = "";
    /**
     * <code>string stringTypeField = 7;</code>
     * @return The stringTypeField.
     */
    public String getStringTypeField() {
      Object ref = stringTypeField_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stringTypeField_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string stringTypeField = 7;</code>
     * @return The bytes for stringTypeField.
     */
    public com.google.protobuf.ByteString
        getStringTypeFieldBytes() {
      Object ref = stringTypeField_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stringTypeField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stringTypeField = 7;</code>
     * @param value The stringTypeField to set.
     * @return This builder for chaining.
     */
    public Builder setStringTypeField(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stringTypeField_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stringTypeField = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringTypeField() {
      
      stringTypeField_ = getDefaultInstance().getStringTypeField();
      onChanged();
      return this;
    }
    /**
     * <code>string stringTypeField = 7;</code>
     * @param value The bytes for stringTypeField to set.
     * @return This builder for chaining.
     */
    public Builder setStringTypeFieldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stringTypeField_ = value;
      onChanged();
      return this;
    }

    private java.util.List<ProtoObject> listObjectTypeField_ =
      java.util.Collections.emptyList();
    private void ensureListObjectTypeFieldIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        listObjectTypeField_ = new java.util.ArrayList<ProtoObject>(listObjectTypeField_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ProtoObject, ProtoObject.Builder, ProtoObjectOrBuilder> listObjectTypeFieldBuilder_;

    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public java.util.List<ProtoObject> getListObjectTypeFieldList() {
      if (listObjectTypeFieldBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listObjectTypeField_);
      } else {
        return listObjectTypeFieldBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public int getListObjectTypeFieldCount() {
      if (listObjectTypeFieldBuilder_ == null) {
        return listObjectTypeField_.size();
      } else {
        return listObjectTypeFieldBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public ProtoObject getListObjectTypeField(int index) {
      if (listObjectTypeFieldBuilder_ == null) {
        return listObjectTypeField_.get(index);
      } else {
        return listObjectTypeFieldBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder setListObjectTypeField(
        int index, ProtoObject value) {
      if (listObjectTypeFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.set(index, value);
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder setListObjectTypeField(
        int index, ProtoObject.Builder builderForValue) {
      if (listObjectTypeFieldBuilder_ == null) {
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.set(index, builderForValue.build());
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder addListObjectTypeField(ProtoObject value) {
      if (listObjectTypeFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.add(value);
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder addListObjectTypeField(
        int index, ProtoObject value) {
      if (listObjectTypeFieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.add(index, value);
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder addListObjectTypeField(
        ProtoObject.Builder builderForValue) {
      if (listObjectTypeFieldBuilder_ == null) {
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.add(builderForValue.build());
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder addListObjectTypeField(
        int index, ProtoObject.Builder builderForValue) {
      if (listObjectTypeFieldBuilder_ == null) {
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.add(index, builderForValue.build());
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder addAllListObjectTypeField(
        Iterable<? extends ProtoObject> values) {
      if (listObjectTypeFieldBuilder_ == null) {
        ensureListObjectTypeFieldIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listObjectTypeField_);
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder clearListObjectTypeField() {
      if (listObjectTypeFieldBuilder_ == null) {
        listObjectTypeField_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public Builder removeListObjectTypeField(int index) {
      if (listObjectTypeFieldBuilder_ == null) {
        ensureListObjectTypeFieldIsMutable();
        listObjectTypeField_.remove(index);
        onChanged();
      } else {
        listObjectTypeFieldBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public ProtoObject.Builder getListObjectTypeFieldBuilder(
        int index) {
      return getListObjectTypeFieldFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public ProtoObjectOrBuilder getListObjectTypeFieldOrBuilder(
        int index) {
      if (listObjectTypeFieldBuilder_ == null) {
        return listObjectTypeField_.get(index);  } else {
        return listObjectTypeFieldBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public java.util.List<? extends ProtoObjectOrBuilder>
         getListObjectTypeFieldOrBuilderList() {
      if (listObjectTypeFieldBuilder_ != null) {
        return listObjectTypeFieldBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listObjectTypeField_);
      }
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public ProtoObject.Builder addListObjectTypeFieldBuilder() {
      return getListObjectTypeFieldFieldBuilder().addBuilder(
          ProtoObject.getDefaultInstance());
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public ProtoObject.Builder addListObjectTypeFieldBuilder(
        int index) {
      return getListObjectTypeFieldFieldBuilder().addBuilder(
          index, ProtoObject.getDefaultInstance());
    }
    /**
     * <code>repeated .ProtoObject listObjectTypeField = 8;</code>
     */
    public java.util.List<ProtoObject.Builder>
         getListObjectTypeFieldBuilderList() {
      return getListObjectTypeFieldFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ProtoObject, ProtoObject.Builder, ProtoObjectOrBuilder>
        getListObjectTypeFieldFieldBuilder() {
      if (listObjectTypeFieldBuilder_ == null) {
        listObjectTypeFieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ProtoObject, ProtoObject.Builder, ProtoObjectOrBuilder>(
                listObjectTypeField_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        listObjectTypeField_ = null;
      }
      return listObjectTypeFieldBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SampleProtoObjectForTest)
  }

  // @@protoc_insertion_point(class_scope:SampleProtoObjectForTest)
  private static final SampleProtoObjectForTest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SampleProtoObjectForTest();
  }

  public static SampleProtoObjectForTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SampleProtoObjectForTest>
      PARSER = new com.google.protobuf.AbstractParser<SampleProtoObjectForTest>() {
    @Override
    public SampleProtoObjectForTest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SampleProtoObjectForTest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SampleProtoObjectForTest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SampleProtoObjectForTest> getParserForType() {
    return PARSER;
  }

  @Override
  public SampleProtoObjectForTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

