// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleProtoObjectsForTest.proto

package com.tosan.redissoncodectest.protoEntities;

public final class SampleProtoObjectsForTest {
  private SampleProtoObjectsForTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleProtoObjectForTest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleProtoObjectForTest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037SampleProtoObjectsForTest.proto\"\353\001\n\030Sa" +
      "mpleProtoObjectForTest\022\027\n\017doubleTypeFiel" +
      "d\030\001 \001(\001\022\026\n\016floatTypeField\030\002 \001(\002\022\024\n\014intTy" +
      "peField\030\003 \001(\005\022\025\n\rlongTypeField\030\004 \001(\003\022\025\n\r" +
      "boolTrueField\030\005 \001(\010\022\026\n\016boolFalseField\030\006 " +
      "\001(\010\022\027\n\017stringTypeField\030\007 \001(\t\022)\n\023listObje" +
      "ctTypeField\030\010 \003(\0132\014.ProtoObject\"\277\001\n\013Prot" +
      "oObject\022 \n\nnull_value\030\001 \001(\0162\n.NullValueH" +
      "\000\022\026\n\014double_value\030\002 \001(\001H\000\022\025\n\013float_value" +
      "\030\003 \001(\002H\000\022\026\n\014string_value\030\004 \001(\tH\000\022\024\n\nbool" +
      "_value\030\005 \001(\010H\000\022\023\n\tint_value\030\006 \001(\005H\000\022\024\n\nl" +
      "ong_value\030\007 \001(\003H\000B\006\n\004kind*\033\n\tNullValue\022\016" +
      "\n\nNULL_VALUE\020\000B-\n)com.tosan.redissoncode" +
      "ctest.protoEntitiesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SampleProtoObjectForTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleProtoObjectForTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleProtoObjectForTest_descriptor,
        new String[] { "DoubleTypeField", "FloatTypeField", "IntTypeField", "LongTypeField", "BoolTrueField", "BoolFalseField", "StringTypeField", "ListObjectTypeField", });
    internal_static_ProtoObject_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoObject_descriptor,
        new String[] { "NullValue", "DoubleValue", "FloatValue", "StringValue", "BoolValue", "IntValue", "LongValue", "Kind", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
